const countriesList = {
  nome: "Brasil",
  idd: "+55",
  cep: {
    formato: "#####-###",
    regex: "^\\d{5}-\\d{3}$",
  },
  estados: [
    {
      sigla: "SP",
      nome: "São Paulo",
      cidades: [
        "São Paulo",
        "Campinas",
        "São Bernardo do Campo",
        "Santos",
        "São José dos Campos",
        "Sorocaba",
        "Ribeirão Preto",
        "São José do Rio Preto",
        "Mogi das Cruzes",
        "Piracicaba",
      ],
    },
    {
      sigla: "RJ",
      nome: "Rio de Janeiro",
      cidades: [
        "Rio de Janeiro",
        "Niterói",
        "Duque de Caxias",
        "Nova Iguaçu",
        "São Gonçalo",
        "Belford Roxo",
        "Campos dos Goytacazes",
        "Petrópolis",
        "Angra dos Reis",
        "Macaé",
      ],
    },
    {
      sigla: "MG",
      nome: "Minas Gerais",
      cidades: [
        "Belo Horizonte",
        "Uberlândia",
        "Contagem",
        "Juiz de Fora",
        "Betim",
        "Montes Claros",
        "Divinópolis",
        "Ipatinga",
        "Uberaba",
        "Governador Valadares",
      ],
    },
    {
      sigla: "BA",
      nome: "Bahia",
      cidades: [
        "Salvador",
        "Feira de Santana",
        "Vitória da Conquista",
        "Camaçari",
        "Itabuna",
        "Juazeiro",
        "Ilhéus",
        "Porto Seguro",
        "Lauro de Freitas",
        "Jequié",
      ],
    },
    {
      sigla: "PR",
      nome: "Paraná",
      cidades: [
        "Curitiba",
        "Londrina",
        "Maringá",
        "Ponta Grossa",
        "Cascavel",
        "Foz do Iguaçu",
        "Guarapuava",
        "São José dos Pinhais",
        "Colombo",
        "Paranaguá",
      ],
    },
    {
      sigla: "RS",
      nome: "Rio Grande do Sul",
      cidades: [
        "Porto Alegre",
        "Caxias do Sul",
        "Pelotas",
        "Canoas",
        "Santa Maria",
        "Novo Hamburgo",
        "São Leopoldo",
        "Rio Grande",
        "Passo Fundo",
        "Bagé",
      ],
    },
    {
      sigla: "CE",
      nome: "Ceará",
      cidades: [
        "Fortaleza",
        "Caucaia",
        "Juazeiro do Norte",
        "Maracanaú",
        "Sobral",
        "Crato",
        "Itapipoca",
        "Russas",
        "Icó",
        "Quixadá",
      ],
    },
    {
      sigla: "PE",
      nome: "Pernambuco",
      cidades: [
        "Recife",
        "Jaboatão dos Guararapes",
        "Olinda",
        "Caruaru",
        "Petrolina",
        "Paulista",
        "Cabo de Santo Agostinho",
        "Igarassu",
        "Vitória de Santo Antão",
        "Garanhuns",
      ],
    },
    {
      sigla: "PA",
      nome: "Pará",
      cidades: [
        "Belém",
        "Ananindeua",
        "Santarém",
        "Marabá",
        "Parauapebas",
        "Castanhal",
        "Itaituba",
        "Altamira",
        "Bragança",
        "Abaetetuba",
      ],
    },
    {
      sigla: "DF",
      nome: "Distrito Federal",
      cidades: ["Brasília"],
    },
    {
      sigla: "ES",
      nome: "Espírito Santo",
      cidades: [
        "Vitória",
        "Vila Velha",
        "Serra",
        "Cariacica",
        "Guarapari",
        "Colatina",
        "Linhares",
        "São Mateus",
        "Viana",
        "Cachoeiro de Itapemirim",
      ],
    },
    {
      sigla: "GO",
      nome: "Goiás",
      cidades: [
        "Goiânia",
        "Aparecida de Goiânia",
        "Anápolis",
        "Rio Verde",
        "Luziânia",
        "Catalão",
        "Formosa",
        "Itumbiara",
        "Águas Lindas de Goiás",
        "Caldas Novas",
      ],
    },
    {
      sigla: "MA",
      nome: "Maranhão",
      cidades: [
        "São Luís",
        "Imperatriz",
        "Caxias",
        "Timon",
        "Codó",
        "Paço do Lumiar",
        "Bacabal",
        "Santa Inês",
        "Balsas",
        "Barreirinhas",
      ],
    },
    {
      sigla: "MT",
      nome: "Mato Grosso",
      cidades: [
        "Cuiabá",
        "Várzea Grande",
        "Rondonópolis",
        "Sinop",
        "Tangará da Serra",
        "Lucas do Rio Verde",
        "Barra do Garças",
        "Cáceres",
        "Sorriso",
        "Alta Floresta",
      ],
    },
    {
      sigla: "MS",
      nome: "Mato Grosso do Sul",
      cidades: [
        "Campo Grande",
        "Dourados",
        "Três Lagoas",
        "Corumbá",
        "Ponta Porã",
        "Naviraí",
        "Aquidauana",
        "Nova Andradina",
        "Paranaíba",
        "Sidrolândia",
      ],
    },
    {
      sigla: "PB",
      nome: "Paraíba",
      cidades: [
        "João Pessoa",
        "Campina Grande",
        "Santa Rita",
        "Patos",
        "Bayeux",
        "Sousa",
        "Cabedelo",
        "Guarabira",
        "Cajazeiras",
        "Pombal",
      ],
    },
    {
      sigla: "PE",
      nome: "Pernambuco",
      cidades: [
        "Recife",
        "Jaboatão dos Guararapes",
        "Olinda",
        "Caruaru",
        "Petrolina",
        "Paulista",
        "Cabo de Santo Agostinho",
        "Igarassu",
        "Vitória de Santo Antão",
        "Garanhuns",
      ],
    },
    {
      sigla: "PI",
      nome: "Piauí",
      cidades: [
        "Teresina",
        "Parnaíba",
        "Picos",
        "Promissão",
        "Valença do Piauí",
        "Campo Maior",
        "Floriano",
        "Corrente",
        "Esperantina",
        "José de Freitas",
      ],
    },
    {
      sigla: "RN",
      nome: "Rio Grande do Norte",
      cidades: [
        "Natal",
        "Mossoró",
        "Parnamirim",
        "São Gonçalo do Amarante",
        "Macaíba",
        "Ceará-Mirim",
        "Santa Cruz",
        "São José de Mipibu",
        "Caicó",
        "Assu",
      ],
    },
    {
      sigla: "RO",
      nome: "Rondônia",
      cidades: [
        "Porto Velho",
        "Ji-Paraná",
        "Ariquemes",
        "Vilhena",
        "Cacoal",
        "Jaru",
        "Rolim de Moura",
        "Machadinho D'Oeste",
        "Costa Marques",
        "Buritis",
      ],
    },
    {
      sigla: "RR",
      nome: "Roraima",
      cidades: [
        "Boa Vista",
        "Rorainópolis",
        "Caracaraí",
        "Mucajaí",
        "Iracema",
        "Pacaraima",
        "São Luiz do Anauá",
        "Normandia",
        "Alto Alegre",
        "Amajarí",
      ],
    },
    {
      sigla: "AP",
      nome: "Amapá",
      cidades: [
        "Macapá",
        "Santana",
        "Laranjal do Jari",
        "Oiapoque",
        "Mazagão",
        "Calçoene",
        "Tartarugalzinho",
        "Porto Grande",
        "Vitória do Jari",
        "Pracuúba",
      ],
    },
    {
      sigla: "AC",
      nome: "Acre",
      cidades: [
        "Rio Branco",
        "Cruzeiro do Sul",
        "Sena Madureira",
        "Tarauacá",
        "Feijó",
        "Brasiléia",
        "Xapuri",
        "Plácido de Castro",
        "Epitaciolândia",
        "Mâncio Lima",
      ],
    },
    {
      sigla: "AL",
      nome: "Alagoas",
      cidades: [
        "Maceió",
        "Arapiraca",
        "Rio Largo",
        "Palmeira dos Índios",
        "Penedo",
        "Maragogi",
        "São Miguel dos Campos",
        "Delmiro Gouveia",
        "Coruripe",
        "União dos Palmares",
      ],
    },
    {
      sigla: "SE",
      nome: "Sergipe",
      cidades: [
        "Aracaju",
        "Nossa Senhora do Socorro",
        "Lagarto",
        "Estância",
        "Itabaiana",
        "São Cristóvão",
        "Propriá",
        "Nossa Senhora da Glória",
        "Alegrete",
        "Capela",
      ],
    },
    {
      sigla: "TO",
      nome: "Tocantins",
      cidades: [
        "Palmas",
        "Araguaína",
        "Gurupi",
        "Porto Nacional",
        "Paraíso do Tocantins",
        "Colinas do Tocantins",
        "Araguatins",
        "Guaraí",
        "Miracema do Tocantins",
        "Augustinópolis",
      ],
    },
  ],
};

export default countriesList;
